name: Deploy to Target Node

on:
  workflow_call:

jobs:
  deploy:
    name: Deploy & Verify to VM2 (Pure Native)
    runs-on: self-hosted
    env:
      SSH_OPTS: "-o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o BatchMode=yes -i ~/.ssh/id_rsa"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Prepare VM2 & Deploy
        run: |
          export SSH_AUTH_SOCK=""
          HOST="${{ secrets.TARGET_USER }}@${{ secrets.TARGET_HOST }}"

          CURRENT_TIME=$(date +"%Y-%m-%d %H:%M:%S")

          scp $SSH_OPTS docker-compose.yml nginx.conf scripts/setup-target.sh $HOST:/tmp/

          ssh $SSH_OPTS $HOST "
            set -e

            sudo date -s \"$CURRENT_TIME\"
            sudo timedatectl set-ntp false || true
            sleep 2

            sudo systemctl stop unattended-upgrades || true

            for i in {1..12}; do
              if ! sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; then
                break
              fi
              sleep 5
            done

            sudo rm -f /var/lib/dpkg/lock-frontend
            sudo rm -f /var/lib/apt/lists/lock
            sudo rm -f /var/lib/dpkg/lock
            sudo dpkg --configure -a

            chmod +x /tmp/setup-target.sh
            sudo /tmp/setup-target.sh

            sudo ufw disable || true

            sudo mkdir -p /opt/mywebapp
            sudo mv /tmp/docker-compose.yml /tmp/nginx.conf /opt/mywebapp/

            cd /opt/mywebapp
            echo '${{ secrets.GITHUB_TOKEN }}' | sudo docker login ghcr.io -u '${{ github.actor }}' --password-stdin
            sudo docker compose pull
            sudo systemctl restart mywebapp.service

            sleep 3
            sudo docker compose ps
          "

      - name: Verify deployment
        run: |
          TARGET_IP="${{ secrets.TARGET_HOST }}"

          for i in {1..30}; do
            STATUS_MAIN=$(curl -o /dev/null -s -w '%{http_code}' http://$TARGET_IP:8080/)
            STATUS_HEALTH=$(curl -o /dev/null -s -w '%{http_code}' http://$TARGET_IP:8080/health/alive)

            if [ "$STATUS_MAIN" -eq 200 ] && [ "$STATUS_HEALTH" -eq 403 ]; then
              echo "App is ready (200 OK) and health is blocked (403 Forbidden)"
              exit 0
            fi

            echo "Очікування запуску... спроба $i/30"
            sleep 5
          done

          echo "Помилка верифікації!"
          exit 1
